#Esto es para nombrar nuestro workflow es decir para nombrar las tareas o
#el conjunto de tareas que se van a estar ejecutando
name: CI

# Esto es para decirle en que evento se van a ejecutar las tareas
on:
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:
    #Definición de variables de entorno
    env:
      platform: aws
      region: us-east-1
      account: 1224343544

      #Variables secretas del repo settings > Secrets an variable > Actions > New repository secret
      username: ${{ secrets.USERNAME }}
      password: ${{ secrets.PASSWORD }}
    # EL entorno donde se ejecutará el trabajo
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: "Mostrar mensage"
        run: echo "Hola mundo"
      - name: "Mostrando variables de entorno"
        #Condicionales
        if: ${{ env.platform == 'azure' }} 
        run: |
          echo "Plataforma ${{ env.platform }}"
          echo "Region ${{ env.region }}"
          echo "Cuenta ${{ env.account }}"
      - name: "Mostrando variables por defecto"
        run: |
          echo "Evento: ${{ github.event }}"
          echo "Envent2 ${{ toJson(github.event) }}"
          echo "GITHUB_ACTOR: ${{ github.actor }}"
          echo "GITHUB_ACTOR: $GITHUB_ACTOR"
          echo "GITHUB_REPOSITORY: ${{ github.repository }}"

      - name: "Mostrando variables de entorno secretas"
        if: ${{ env.username == 'duberly' }}
        #No muestra estas variables pero si las lee
        run: |
            echo "My username: ${{ env.username  }}"
            echo "My password: ${{ env.password }}"
      - name: "Montrando variables de entorno públicas"
        run: echo "${{ vars.PROJECT_VERSION }}"

